### ISSUE TITLE
sm2解密提示invalid cipher text

### ISSUE THREAD

**Issue by TenshiKnight** [Zirconium233/yunForNewVersion#26]
![35B9BDAB39DDA33FB479A6EC08EF6368](https://github.com/user-attachments/assets/7feec70c-cdde-4841-864b-6db7922e0f73)

检查过公钥私钥，自己抓包的cipherKey也检查过，解密网站总是提示invalid cipher text

**Comment by Zirconium233** [comment]
这个README.md里面说过了，选c1c3c2模式。

**Comment by TenshiKnight** [comment]
我真是眼瞎了。。，谢谢你！
