### ISSUE TITLE
跑步失败了:data

### ISSUE THREAD

**Issue by Lampotaku** [Zirconium233/yunForNewVersion#28]
![QQ20241103-195339](https://github.com/user-attachments/assets/9abaddea-5857-4f5e-ac03-fc25659081d1)
使用的为打表模式，同时在task_else中配置好了同学跑步的数据，还是报错data

**Comment by Zirconium233** [comment]
这是登录问题，检查你的token，deviceid，uuid参数。一般这种包都post不上去的代码运行问题，直接开debug就能解决。

**Comment by Lampotaku** [comment]
![微信图片_20241103203202](https://github.com/user-attachments/assets/0fcb0c63-beb9-4551-8d68-100e9257f26f)
检查了token，现在可以跑起来了。只不过抓的数据是同一个，左侧是我自己的，右侧是原数据来源，被判定不合格，是否是因为开了随机偏移导致里程判定不足？

**Comment by Zirconium233** [comment]
应该就是这个原因。目前不建议开里程偏移，因为这个里程偏移算法写的很一般。
