### ISSUE TITLE
提供了一个更具保障性的加密解密库

### ISSUE THREAD

**Issue by Pectics** [Zirconium233/yunForNewVersion#31]
使用C++实现，生成的`.pyd`文件可由Python直接调用，具体使用查看：
[CryptUtils](https://github.com/Pectics/CryptUtils)

虽然感觉意义不大，但是可以简化一下`main.py`中的代码

**Comment by Zirconium233** [comment]
我还以为你是把加解密算法自己写了一遍...原来也是gm包(用这个还要考虑验签能不能过)。确实意义不大，如果是cmake组织的项目可以考虑使用(还是直接生成命令行调用exe方便，或者用qt做个界面)，不过vs组织的项目........这是完全不考虑Linux.......c++一般是造轮子的，换c++调包，哪天环境一变给你跳99+error就老实了。大多数情况下是徒增debug难度。毕竟首先日常脚本方便为主不考虑速度，而且真考虑速度瓶颈大头也在网络上。
