### ISSUE TITLE
data报错

### ISSUE THREAD

**Issue by Wfscl0** [Zirconium233/yunForNewVersion#35]
不管什么模式都一直data报错

**Comment by Zirconium233** [comment]
那就是登录token问题

**Comment by Zirconium233** [comment]
应该和学校部署的server有关系，我这边使用3.3.1一切正常

**Comment by chatseeon** [comment]
> 试试吧config的app_edition改成3.4.5，应该是版本号变了，请求"/run/getHomeRunInfo"返回了个版本过低

测试可用，好像是因为3.4.5是强制更新版本。
